dist: xenial
language: python
python:
- '3.6.9'
install:
- pip install -r requirements.txt
script:
- /bin/bash -c ci/run.sh
deploy:
  provider: pypi
  user: dvasilik
  password:
    secure: RTu+mZ57Gf/i70TpZfgvosERfSAbeZSd1jIL1hbx3T3xDWAjnJj8DDq+/eWjeiMtv6JDV6MZmU9VoAGw2MwgVg4noNrPpcNQVPhwnoViLoUnpHXvIDZIbbJI1SSqFB+uSgP7b3kD6+61cR6Nijuz2UXLm8uxs4PJqOmsbIeCQOYkR5QfB5jX7Pa3SGEzo0oSODtCV7jrn/uw9It8QZ5wmkZa3cAhLB2ZJ/jVmbgqcaT8nreyzdbQyDlxpE5yNhErswTwK8gI1roEOUn4tyatqbcRGAx95tuAG/1FjwMfGz7P6oHPD31SXkYFOV2P0i/n8FETwKMAtdZ5V5zMLy0KlBsp+Bthkf16KOYNBOCZ7z9j1KOKSi+stN1bLR/VZ3j6kNrZrG6i1hN2m+mcHZuYh4dBzzI3N/reqnat6+a6JVP4SdTEAj8hys2raNM86Ld/GtLy1LFKJFaKWMwuARmkp90CsK0hB35qKxsVIkrsDMAmYDNnusoFaw/MnaLATqYK9Kgq8okt7Mj0uQKM2d3USMHCvY8RqcFSvLjMiwyiuJu6OxEJdOdu2w6ACob8XmNfZMgZLKQy06p2yZi1oUr9IkSzs6qNTYlIMGH51qIQEHIy1RIKwqmYrZ3Van4RonChbiuDSPLOBBwyWRAlC8mnM0Cqkx+aXw7x3Nd0AqwKcuU=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
  skip_existing: true
  skip_cleanup: true
