dist: xenial
language: python
python:
- 3.6.9
- '3.7'
install:
- pip install -r requirements.txt
script:
- "/bin/bash -c ci/run.sh"
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "z+MAS286Z19APXKfdUwEpNVOW0RxzipFmPw6Ihr2ok2qwJqVFBFqblKelJY3TsMuOHU7gjAW6KVlUPWgAzwPqrzp2J+kWbTRNn/WaLiddLLo2J8V5WrsWi5Ed2O6VZaj0Z2WDKldwM0wMEtXfvs6/z2/cq0dHAZGNcf4mYV12KCeCWCfIByXfeOqFNmNtl9PmAs85v9P8l7/m+euE40882T6J7rDu8iC42XdXCH3y1oBQ1VSgMUQtX14G38mpVWt5UfJn7e8cnRwdK49qcupaTW0JorJ7IPJ+7bVxIl5plyZOgAss+oa25tfPeN6TmJCpazm4/LH+Ztf6ydpX+QXpR5itbzZ8X8AtNYM5L4flmefcGd2nF8NfvMYmkb2bWc9tUcxqX6NMIJrB6QopFosXPzM+fNlL2/tlK5S+lO9HiLLvyP/1HcxOookrzOyZaY6UHp/PoyJ+OxLTrJMpJdN3oYIvlRn5UYNgwCJ6NpLY1P2wvA3gqo81YhpoSSMOebAH5uZUXNg+tLofOgX9GhoIdp4y/8xtXeKqVIoQ3ZPb2jVhUQ08L/J1MituPJjCU/LzOto3MnXoMyN2gNWUmv+p+Vns1xCVOTkcwwdwlruLMNu2UjWCAKCUC01IWI5jgRQGKuPSaVz3bkh5RR/NKsqLYd3tkW2m7ZAVsK8mwDkvIY="
  distributions: sdist bdist_wheel
  on:
    tags: true
  skip_existing: true
  skip_cleanup: true
