dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
- pip install -r requirements.txt
script:
- "./ci/run.sh"
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: dvasilik
  password:
    secure: FmRIpQ5HJK8yCC7d1D0wS5U5RRfBBr6Opd0kkdW0vI7CQlAy4JsEdGkhTDE6jUkIa64LX1/HCl7FcSX7WqQA+HFb79BQjqnkGpqSj30eqWtHWnfldk84V+G0ukZaCUfT5FV0Xe9MWmYzTb9AEhbHpI8bR3B/baEs8JPWE6AsoMqW6pStRnmzYBsO1vKJFVGLYFtwV5Kimxae2dcbhcZkALVOoE/DSId3iFH2/N0SDiz37WKwLdY1irKKZTpyGwZn74JeX8brerW41jZucZuZ9i3iSbaYps+YGpxaAG4PkB67iU30LBi7AQ9sAtB3ba+UrpfhtyIkIuSYS2WRYFgUYFRhkWYe8l/Y3a64atFoSIgsWnKOhqVkQQCrkhbHH2CS3MOO4J3H66QrZHlGYqFPIBanONugUXG1L7HkzPvbwx0PE8Fd0btV5XoHmjenFgZbJDn3S6Ae0B4GsDCuRcUmMj4TLdfqpTjX27WbZwewx6dcQPwCv6IN07KpiVblDrcp8qsIGK0kiV81M73AyvgNgIuet949zfkPBzBpkKvxEnzul4vAjf7ulMbJT2qfq7u01mJpRmTVK6BH+SEGXscx/NX6zrB0RClt5KeqbF02LB6TcLa3P/LNt9YXZOe8q3kApQ4pNSzdZ8ycq6GbfX6G8TxTh2pwYYGycQ80uHIgchc=
  on:
    tags: true
  skip_existing: true
  skip_cleanup: true
